[package]
name = "lightning-background-processor"
version = "0.0.104"
authors = ["Valentine Wallace <vwallace@protonmail.com>"]
license = "MIT OR Apache-2.0"
repository = "http://github.com/lightningdevkit/rust-lightning"
description = """
Utilities to perform required background tasks for Rust Lightning.
"""
edition = "2018"

[dependencies]
bitcoin = "0.27"
lightning = { version = "0.0.104", path = "../lightning", features = ["std"] }
lightning-persister = { version = "0.0.104", path = "../lightning-persister" }

[dev-dependencies]
lightning = { version = "0.0.104", path = "../lightning", features = ["_test_utils"] }
lightning-invoice = { version = "0.12.0", path = "../lightning-invoice" }
